env:
  singleUserMode: "true"
  registration: {}
  # emailDomainBlacklist: "example1.com|example2.com"
  # emailDomainWhitelist: "example1.com|example2.com"
  defaultLanguage: "ja"
  smtp:
    server: ""
    port: "587"
    login: ""
    address: ""
    reply_to: ""
    opensslVerifyMode: "peer"
    aliasHostname: ""
    domain: ""
  assets: {}
  # paperclipRootPath: "/var/lib/mastodon/public-system"
  # paperclipRootUrl: "system"
  # cdnHost: "assets.example.com"
  s3:
    enabled: true
    # These come from minio by default, set here to override
    bucket: ""
    awsAccessKeyId: ""
    awsSecretAccessKey: ""
    endpoint: ""
    region: ""
    protocol: "http"
    hostname: "mastodon-minio:9000"

httpd:
  name: assets
  servicePort: 80
  containerPort: 80
  resources:
    requests:
      memory: 32Mi
      cpu: 50m

web:
  image: registry.digitalocean.com/rgst/mastodon
  imageTag: latest
  imagePullPolicy: IfNotPresent
  servicePort: 80
  containerPort: 3000
  concurrency: 5
  maxThreads: 5
  logLevel: info
  keepMediaDays: 7
  maintenanceHour: 3
  ingress:
    host: SET_YOUR_DOMAIN
  persistentVolume:
    system:
      accessMode: ReadWriteOnce
      size: 8Gi
    assets:
      accessMode: ReadWriteOnce
      size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
streaming:
  image: registry.digitalocean.com/rgst/mastodon
  imageTag: latest
  imagePullPolicy: IfNotPresent
  servicePort: 4000
  containerPort: 4000
  clusterSize: 5
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
sidekiq:
  image: registry.digitalocean.com/rgst/mastodon
  imageTag: latest
  imagePullPolicy: IfNotPresent
  parallelism: 2
  defaultQparallelism: 2
  pullQparallelism: 5
  pushQparallelism: 2
  mailersQparallelism: 2
  defaultQreplicas: 1
  pullQreplicas: 1
  pushQreplicas: 1
  mailersQreplicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
redis:
  enabled: true
  image:
    tag: 6-alpine
  servicePort: 6379
  containerPort: 6379
  storage:
    requestedSize: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

postgres:
  enabled: true
  image:
    tag: "13.1"
  imagePullPolicy: IfNotPresent
  userDatabase:
    name: mastodon
    user: mastodon
  storage:
    requestedSize: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

elasticsearch:
  enabled: true
  storage:
    requestedSize: 10Gi

minio:
  enabled: true

  # CHANGE ME!!
  accessKey: BkU9Gc8wIygQC8kghBhN
  secretKey: mOGpRFdMyyiBDTXdhBZIDGU9uWHqVtauYvBDgPgO

  enabled: true
  ingress:
    enabled: true
  defaultBucket:
    enabled: true
    name: mastodon

### Secrets, change these.
postgresPassword: ""
redisPassword: ""
paperclipSecret: "" 
secretKeyBase: ""
otpSecret: ""
smtpPassword: ""