apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: main
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "web"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "web.fullname" . }}
spec:
  rules:
  - host: {{ .Values.web.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "fullname" . }}-web
            port: 
              name: http
      - path: /api/v1/streaming
        pathType: Prefix
        backend:
          service:
            name: {{ template "fullname" . }}-streaming
            port: 
              name: http
  tls:
  - secretName: {{ template "name" . }}-tls
    hosts:
    - {{ .Values.web.ingress.host }}
