apiVersion: batch/v1beta1
kind: CronJob
metadata:
metadata:
  name: {{ template "name" . }}-maintenance
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "0 {{ .Values.web.maintenanceHour }} * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          {{- if or (eq "ReadWriteOnce" .Values.web.persistentVolume.assets.accessMode) (eq "ReadWriteOnce" .Values.web.persistentVolume.system.accessMode) }}
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
          {{- end }}
          restartPolicy: OnFailure
          containers:
          - name: {{ template "name" . }}-maintenance
            image: "{{ .Values.web.image }}:{{ .Values.web.imageTag }}"
            imagePullPolicy: {{ .Values.web.imagePullPolicy | quote }}
            command: ["/bin/sh"]
            args:
            - "-c"
            - "tootctl media remove --days={{ .Values.web.keepMediaDays }} && tootctl statuses remove"
            envFrom:
            - configMapRef:
                name: {{ include "fullname" . }}-env
            - secretRef:
                name: {{ include "fullname" . }}-web
            volumeMounts:
            - name: assets
              mountPath: /mastodon/public/assets
          volumes:
          - name: assets
            persistentVolumeClaim:
              claimName: {{ template "web.fullname" . }}-assets
