apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "name" . }}-post-upgrade
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app: {{ template "name" . }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      {{- if or (eq "ReadWriteOnce" .Values.web.persistentVolume.assets.accessMode) (eq "ReadWriteOnce" .Values.web.persistentVolume.system.accessMode) }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: component
                  operator: In
                  values:
                    - web
            topologyKey: kubernetes.io/hostname
      {{- end }}
      containers:
      - name: {{ template "name" . }}-post-upgrade-job
        image: "{{ .Values.web.image }}:{{ .Values.web.imageTag }}"
        imagePullPolicy: {{ .Values.web.imagePullPolicy | quote }}
        command: ["/bin/sh"]
        args:
          - "-c"
          - "bundle exec rails db:migrate && bundle exec rails assets:precompile"
        envFrom:
          - configMapRef:
              name: {{ include "fullname" . }}-env
          - secretRef:
              name: {{ include "fullname" . }}-web
        volumeMounts:
        - name: assets
          mountPath: /mastodon/public/assets
      volumes:
      - name: assets
        persistentVolumeClaim:
          claimName: {{ template "web.fullname" . }}-assets
