apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "web"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "web.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.web.servicePort }}
      targetPort: http
  selector:
    app: {{ template "name" . }}
    component: "web"
    release: {{ .Release.Name }}
  type: "ClusterIP"
